/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Users {
  email: string;
  id: Generated<string>;
  name: string | null;
  password: string | null;
}

export interface Objectives {
  title: string;
  id: Generated<string>;
  description: string | null;
  creatorId: string;
  notifyAt: Date | null;
  createdAt: Date | null;
  updatedAt: Date | null;
  isCompleted: boolean | null;
}

export interface DB {
  users: Users;
  objectives: Objectives
}
